default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host: localhost
  username: <%= ENV["USER" ] %>
  password: <%= ENV["DATABASE_PASSWORD" ] %>

development:
  <<: *default
  database: upgradeSb_development

test:
  <<: *default
  database: upgradeSb_test

staging:
  <<: *default
  database: upgradeSb_staging

production:
  <<: *default
  database: upgradeSb_production